### ISSUE TITLE
Añadir el logo de Open Society

### ISSUE THREAD

**Issue by dcabo** [civio/civio.es#5]
No tengo claro en qué lugar hay que hacerlo

**Comment by EvaBelmonte** [comment]
En la ficha de colaboradores, como uno más? Lo hemos hecho con Iurismática

**Comment by dcabo** [comment]
nop, como donante, puede que exijan aparecer en el footer, por ejemplo

**Comment by dcabo** [comment]
No es necesario, así que no lo ponemos. Donal: "You are free to use the OSF logo if you wish to acknowledge our support however we do not insist on you using it if you would not otherwise."
